# Generated by Django 3.2.13 on 2022-09-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_custom_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
