# Generated by Django 3.2.13 on 2022-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220902_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=100),
        ),
    ]
